# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed_0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='u_f2f69ea1', editable=False, max_length=64, unique=True),
        ),
    ]
