# Generated by Django 5.2.7 on 2025-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='u_81302ef8', editable=False, max_length=64, unique=True),
        ),
    ]
