# Generated by Django 5.2.7 on 2025-11-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployed_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployedapp',
            name='app_id',
        ),
    ]
