# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployed_apps', '0001_initial_squashed_0002_remove_deployedapp_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedapp',
            name='app_id',
            field=models.CharField(default='app_0017e7b0', editable=False, max_length=64, unique=True),
        ),
    ]
