# Generated by Django 5.2.7 on 2025-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployed_apps', '0003_deployedapp_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedapp',
            name='app_id',
            field=models.CharField(default='app_ec2fd0a1', editable=False, max_length=64, unique=True),
        ),
    ]
