# Generated by Django 5.2.7 on 2025-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployed_apps', '0004_alter_deployedapp_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedapp',
            name='app_id',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
